version: "3.7"

services:
  mongo:
    image: us.gcr.io/crypto-processor/mongo:latest
    volumes:
      - mongo:/data

  crawler:
    build:
      context: ./crawler
    networks:
      - mongo
      - api
    environment:
      - APP_DEBUG=1

  api:
    build:
      context: ./api
    networks:
      - mongo
      - api

  frontend:
    build:
      context: ./frontend
    networks:
      - nginx
      - api

networks:
  mongo:
  api:
  nginx:

volumes:
  nginx:
  mongo:
  api:
